from duk.instructions.load import *
from duk.instructions.unary import *
from duk.instructions.operator import *
from duk.instructions.ifs import *
from duk.instructions.comparison import *
from duk.instructions.instructions import *
from duk.instructions.blank import *
from duk.instructions.incdec import *

DUK_OP_CLASSES = {
    0: DukInstructionLdReg,
    2: DukInstructionJump,
    3: DukInstructionLdConst, 4: DukInstructionLdInt, 5: DukInstructionLdIntx,
    6: DukInstructionLdThis, 7: DukInstructionLdUndef, 8: DukInstructionLdNull,
    9: DukInstructionLdTrue, 10: DukInstructionLdFalse,
    11: DukInstructionGetVar,
    12: DukInstructionBNot, 13: DukInstructionLNot,
    14: DukInstructionUnm, 15: DukInstructionUnp,
    16: DukInstructionEq, 17: DukInstructionEq, 18: DukInstructionEq, 19: DukInstructionEq,
    20: DukInstructionNeq, 21: DukInstructionNeq, 22: DukInstructionNeq, 23: DukInstructionNeq,
    24: DukInstructionSeq, 25: DukInstructionSeq, 26: DukInstructionSeq, 27: DukInstructionSeq,
    28: DukInstructionSNeq, 29: DukInstructionSNeq, 30: DukInstructionSNeq, 31: DukInstructionSNeq,
    32: DukInstructionGt, 33: DukInstructionGt, 34: DukInstructionGt, 35: DukInstructionGt,
    36: DukInstructionGe, 37: DukInstructionGe, 38: DukInstructionGe, 39: DukInstructionGe,
    40: DukInstructionLt, 41: DukInstructionLt, 42: DukInstructionLt, 43: DukInstructionLt,
    44: DukInstructionLe, 45: DukInstructionLe, 46: DukInstructionLe, 47: DukInstructionLe,
    48: DukInstructionIfTrueR, 49: DukInstructionIfTrueC,
    50: DukInstructionIfFalseR, 51: DukInstructionIfFalseC,
    52: DukInstructionAdd, 53: DukInstructionAdd, 54: DukInstructionAdd, 55: DukInstructionAdd,
    56: DukInstructionSub, 57: DukInstructionSub, 58: DukInstructionSub, 59: DukInstructionSub,
    60: DukInstructionMul, 61: DukInstructionMul, 62: DukInstructionMul, 63: DukInstructionMul,
    64: DukInstructionDiv, 65: DukInstructionDiv, 66: DukInstructionDiv, 67: DukInstructionDiv,
    68: DukInstructionMod, 69: DukInstructionMod, 70: DukInstructionMod, 71: DukInstructionMod,
    72: DukInstructionExp, 73: DukInstructionExp, 74: DukInstructionExp, 75: DukInstructionExp,
    76: DukInstructionBAnd, 77: DukInstructionBAnd, 78: DukInstructionBAnd, 79: DukInstructionBAnd,
    80: DukInstructionBOr, 81: DukInstructionBOr, 82: DukInstructionBOr, 83: DukInstructionBOr,
    84: DukInstructionBXor, 85: DukInstructionBXor, 86: DukInstructionBXor, 87: DukInstructionBXor,
    88: DukInstructionBaSl, 89: DukInstructionBaSl, 90: DukInstructionBaSl, 91: DukInstructionBaSl,
    92: DukInstructionBlSr, 93: DukInstructionBlSr, 94: DukInstructionBlSr, 95: DukInstructionBlSr,
    96: DukInstructionBaSr, 97: DukInstructionBaSr, 98: DukInstructionBaSr, 99: DukInstructionBaSr,
    100: DukInstructionInstOf, 101: DukInstructionInstOf, 102: DukInstructionInstOf, 103: DukInstructionInstOf,
    104: DukInstructionIn, 105: DukInstructionIn, 106: DukInstructionIn, 107: DukInstructionIn,
    108: DukInstructionGetProp, 109: DukInstructionGetProp, 110: DukInstructionGetProp, 111: DukInstructionGetProp,
    112: DukInstructionPutProp, 113: DukInstructionPutProp, 114: DukInstructionPutProp, 115: DukInstructionPutProp,
    116: DukInstructionDelProp, 117: DukInstructionDelProp, 118: DukInstructionDelProp, 119: DukInstructionDelProp, 
    120: DukInstructionPreIncR, 121: DukInstructionPreDecR, 122: DukInstructionPostIncR, 123: DukInstructionPostDecR,
    124: DukInstructionPreIncV, 125: DukInstructionPreDecV, 126: DukInstructionPostIncV, 127: DukInstructionPostDecV,
    128: DukInstructionPreIncP, 129: DukInstructionPreIncP, 130: DukInstructionPreIncP, 131: DukInstructionPreIncP,
    132: DukInstructionPreDecP, 133: DukInstructionPreDecP, 134: DukInstructionPreDecP, 135: DukInstructionPreDecP,
    136: DukInstructionPostIncP, 137: DukInstructionPostIncP, 138: DukInstructionPostIncP, 139: DukInstructionPostIncP,
    140: DukInstructionPostDecP, 141: DukInstructionPostDecP, 142: DukInstructionPostDecP, 143: DukInstructionPostDecP,
    144: DukInstructionDeclVar, 145: DukInstructionDeclVar, 146: DukInstructionDeclVar, 147: DukInstructionDeclVar,
    148: DukInstructionRegExp, 149: DukInstructionRegExp, 150: DukInstructionRegExp, 151: DukInstructionRegExp,
    152: DukInstructionClosure,
    153: DukInstructionTypeOf, 154: DukInstructionTypeOfId,
    155: DukInstructionPutVar, 156: DukInstructionDelVar,
    157: DukInstructionRetReg, 158: DukInstructionRetUndef, 159: DukInstructionRetConst, 160: DukInstructionRetConst,
    161: DukInstructionLabel, 162: DukInstructionEndLabel, 163: DukInstructionBreak, 164: DukInstructionContinue,
    165: DukInstructionTryCatch, 166: DukInstructionEndTry, 167: DukInstructionEndCatch, 168: DukInstructionEndFin,
    169: DukInstructionThrow,
    # 170: DukInstructionInvLhs,
    171: DukInstructionCsReg,
    172: DukInstructionCsVar, 173: DukInstructionCsVar, 174: DukInstructionCsVar, 175: DukInstructionCsVar,
    176: DukInstructionCall, 177: DukInstructionCall, 178: DukInstructionCall, 179: DukInstructionCall, 180: DukInstructionCall,
    181: DukInstructionCall, 182: DukInstructionCall, 183: DukInstructionCall,
    # 184: DukInstructionCall8, 185: DukInstructionCall9, 186: DukInstructionCall10, 187: DukInstructionCall11,
    # 188: DukInstructionCall12, 189: DukInstructionCall13, 190: DukInstructionCall14, 191: DukInstructionCall15,
    192: DukInstructionNewObj, 193: DukInstructionNewArr,
    194: DukInstructionMPutObj,
    # 195: DukInstructionMPutObjI,
    # 196: DukInstructionInitSet,
    # 197: DukInstructionInitGet,
    198: DukInstructionMPutArr,
    # 199: DukInstructionMPutArrI,
    200: DukInstructionSetALen,
    201: DukInstructionInitEnum, 202: DukInstructionNextEnum,
    # 203: DukInstructionNewTarget,
    # 204: DukInstructionDebugger,
    205: DukInstructionNop, 206: DukInstructionInvalid,
    208: DukInstructionGetProp, 209: DukInstructionGetProp, 210: DukInstructionGetProp, 211: DukInstructionGetProp,
}